# Configuration file

# Segundos hasta Respawn (ahora mismo reviven en base a un contador, que puede no siempre ser los mismos segs)
# respawn_time: 5

# Game
game_time: 60
gravity: 0.1

# Personaje
player:
  life: 100
  special_attack_dmg: 100
  speed: 0.5
  run_speed: 1
  jump: 1

# Fantasma 
ghost:
  life: 50
  damage: 10
  speed: 0.25
  prob_carrot: 20 # sobre 100
  prob_ammo: 20 
  prob_goldcoin: 30 
  prob_rocket: 30

# Murcielago
bat:
 life: 20
 damage: 20
 speed: 0.25
 prob_carrot: 10
 prob_ammo: 20
 prob_goldcoin: 50
 prob_rocket: 20

# Mono
monkey:
 life: 50
 damage: 5
 speed: 0
 prob_carrot: 0
 prob_ammo: 25
 prob_goldcoin: 25
 prob_rocket: 25

# GoldCoin
goldcoin:
  add_score: 10

# Zanahoria
carrot:
  add_life: 25

# Municion
ammo:
  add_ammo: 5

rocket_pickup:
  add_ammo: 10

# Balas
bullet:
  speed: 1.5
  damage: 10
  fire_rate: 3 # 2 tiros/seg (500ms de espera)
  initial_ammo: 9999

rocket:
  speed: 1
  damage: 50
  fire_rate: 1 # 4 tiros/seg (250ms de espera)
  initial_ammo: 100

banana:
  speed: 1
  damage: 30
