# Configuration file

# Segundos hasta Respawn (ahora mismo reviven en base a un contador, que puede no siempre ser los mismos segs)
# respawn_time: 5

# Game
game_time: 60
gravity: 0.1

# Personaje
player:
  life: 100
  special_attack_dmg: 100
  speed: 0.5
  run_speed: 1
  jump: 1

# Fantasma 
ghost:
  life: 50
  damage: 10
  speed: 0.25
  prob_carrot: 10 # sobre 100
  prob_ammo: 10 
  prob_goldcoin: 20 
  prob_rocket: 10
  prob_gem: 10
  prob_icebullet: 20

# Murcielago
bat:
  life: 20
  damage: 20
  speed: 0.25
  prob_carrot: 20 # sobre 100
  prob_ammo: 0 
  prob_goldcoin: 10 
  prob_rocket: 10
  prob_gem: 40
  prob_icebullet: 10

# Mono
monkey:
  life: 50
  damage: 5
  speed: 0
  prob_carrot: 30 # sobre 100
  prob_ammo: 0 
  prob_goldcoin: 10 
  prob_rocket: 40
  prob_gem: 10
  prob_icebullet: 10

# GoldCoin
goldcoin:
  add_score: 10

# Zanahoria
carrot:
  add_life: 25

# Municion
ammo:
  add_ammo: 5

# Rocket pickup
rocket_pickup:
  add_ammo: 10

# IceBullet ammo
ice_bullet_ammo:
  add_ammo: 10

# Gem
gem:
  add_score: 25

# Balas
bullet:
  speed: 1.5
  damage: 10
  fire_rate: 3 # 3 tiros/seg (333ms de espera)
  initial_ammo: 9999

rocket:
  speed: 1
  damage: 50
  fire_rate: 1 # 1 tiros/seg (1000ms de espera)
  initial_ammo: 0

ice_bullet:
  speed: 1
  damage: 10
  fire_rate: 1 # 1 tiros/seg (1000ms de espera)
  initial_ammo: 0
  frozen_time: 5 # en seg

banana:
  speed: 1
  damage: 30
